// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// blocking_loop //
// ------------- //

#define blocking_loop_wrap_target 0
#define blocking_loop_wrap 2
#define blocking_loop_pio_version 0

static const uint16_t blocking_loop_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xa0c7, //  1: mov    isr, osr
    0x8020, //  2: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program blocking_loop_program = {
    .instructions = blocking_loop_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = blocking_loop_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config blocking_loop_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + blocking_loop_wrap_target, offset + blocking_loop_wrap);
    return c;
}
#endif

// ------------ //
// blocking_irq //
// ------------ //

#define blocking_irq_wrap_target 0
#define blocking_irq_wrap 2
#define blocking_irq_pio_version 0

static const uint16_t blocking_irq_program_instructions[] = {
            //     .wrap_target
    0x20c4, //  0: wait   1 irq, 4
    0xc044, //  1: irq    clear 4
    0x8020, //  2: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program blocking_irq_program = {
    .instructions = blocking_irq_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = blocking_irq_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config blocking_irq_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + blocking_irq_wrap_target, offset + blocking_irq_wrap);
    return c;
}
#endif

// ------------- //
// blocking_idle //
// ------------- //

#define blocking_idle_wrap_target 0
#define blocking_idle_wrap 0
#define blocking_idle_pio_version 0

static const uint16_t blocking_idle_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program blocking_idle_program = {
    .instructions = blocking_idle_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = blocking_idle_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config blocking_idle_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + blocking_idle_wrap_target, offset + blocking_idle_wrap);
    return c;
}
#endif

