// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// irqtest2 //
// -------- //

#define irqtest2_wrap_target 0
#define irqtest2_wrap 7
#define irqtest2_pio_version 0

static const uint16_t irqtest2_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xa026, //  1: mov    x, isr          side 0
    0xc810, //  2: irq    nowait 0 rel    side 1
    0xd850, //  3: irq    clear 0 rel     side 3
    0x30a0, //  4: wait   1 pin, 0        side 2
    0x2020, //  5: wait   0 pin, 0        side 0
    0x0042, //  6: jmp    x--, 2          side 0
    0x8020, //  7: push   block           side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program irqtest2_program = {
    .instructions = irqtest2_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = irqtest2_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config irqtest2_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + irqtest2_wrap_target, offset + irqtest2_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

