// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// irqtest //
// ------- //

#define irqtest_wrap_target 0
#define irqtest_wrap 8
#define irqtest_pio_version 0

static const uint16_t irqtest_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xa026, //  1: mov    x, isr          side 0
    0x80a0, //  2: pull   block           side 0
    0xa046, //  3: mov    y, isr          side 0
    0x0444, //  4: jmp    x--, 4          side 1
    0xc810, //  5: irq    nowait 0 rel    side 2
    0x0886, //  6: jmp    y--, 6          side 2
    0xd832, //  7: irq    wait 2 rel      side 6
    0xc850, //  8: irq    clear 0 rel     side 2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program irqtest_program = {
    .instructions = irqtest_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = irqtest_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config irqtest_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + irqtest_wrap_target, offset + irqtest_wrap);
    sm_config_set_sideset(&c, 3, false, false);
    return c;
}
#endif

