// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// rxsource //
// -------- //

#define rxsource_wrap_target 0
#define rxsource_wrap 1
#define rxsource_pio_version 0

static const uint16_t rxsource_program_instructions[] = {
            //     .wrap_target
    0x9020, //  0: push   block           side 1
    0xa042, //  1: nop                    side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rxsource_program = {
    .instructions = rxsource_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = rxsource_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rxsource_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rxsource_wrap_target, offset + rxsource_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

