// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// txcount //
// ------- //

#define txcount_wrap_target 0
#define txcount_wrap 5
#define txcount_pio_version 0

static const uint16_t txcount_program_instructions[] = {
            //     .wrap_target
    0xe020, //  0: set    x, 0            side 0
    0x80a0, //  1: pull   block           side 0
    0x1043, //  2: jmp    x--, 3          side 1
    0xa0c1, //  3: mov    isr, x          side 0
    0x8000, //  4: push   noblock         side 0
    0x0001, //  5: jmp    1               side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program txcount_program = {
    .instructions = txcount_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = txcount_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config txcount_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + txcount_wrap_target, offset + txcount_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

